apiVersion: v1
kind: Pod
metadata:
  name: system-test
  namespace: argocd
spec:
  nodeSelector:
    workload: system

  tolerations:
  - key: workload
    operator: Equal
    value: system
    effect: NoSchedule

  containers:
  - name: nginx
    image: nginx
