apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: worker
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/sidharth-sehrawat/projects.git
    targetRevision: master
    path: example-voting-app-gitops/worker

  destination:
    server: https://kubernetes.default.svc
    namespace: worker

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
